In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c =np.intersect1d(a,b) 
c# 找到a,b 相同的项目

array([2, 4])

In [4]:
np.setdiff1d(a,b)   #  从a中删除b存在的项目

array([1, 3, 5, 6])

In [5]:
np.where(a==b)   #找到a，b 中相同元素的位置

(array([1, 3, 5, 7], dtype=int64),)

In [9]:
a = np.arange(15)
np.intersect1d(a,np.arange(5,11))

array([ 5,  6,  7,  8,  9, 10])

In [12]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])  #  向量化
pair_max(a, b)



array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [13]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])